package com.chaibcalligraphy.amanatfaliparent
import android.os.Bundle
import android.webkit.WebView
import android.widget.TextView
import androidx.activity.ComponentActivity
import org.json.JSONArray
import org.json.JSONObject
class MapActivity:ComponentActivity(){
 private lateinit var web:WebView;private lateinit var info:TextView;private var server="";private var token="";private var timer:java.util.Timer?=null
 override fun onCreate(b:Bundle?){super.onCreate(b);setContentView(R.layout.activity_map);web=findViewById(R.id.mapWeb);info=findViewById(R.id.mapInfo);web.settings.javaScriptEnabled=true;web.settings.domStorageEnabled=true;server=intent.getStringExtra("SERVER")?:return;token=intent.getStringExtra("TOKEN")?:return;refresh();timer=java.util.Timer();timer!!.schedule(object:java.util.TimerTask(){override fun run(){runOnUiThread{refresh()}}},30000,30000)}
 private fun refresh(){Api.get(server,"/wp-json/aft/v1/parent-location",token){ok,body->runOnUiThread{if(!ok){info.text="تعذر جلب الموقع: "+body;return@runOnUiThread};try{val o=JSONObject(body);if(!o.optBoolean("has_location",false)){info.text="لم يصل موقع الطفل بعد";return@runOnUiThread};val lat=o.getDouble("latitude");val lng=o.getDouble("longitude");val acc=o.optDouble("accuracy",0.0);val bat=o.optInt("battery",-1);val updated=o.optString("updated_at","—");Api.get(server,"/wp-json/aft/v1/parent-route?limit=300",token){_,rbody->runOnUiThread{val pts=try{JSONObject(rbody).optJSONArray("points")?:JSONArray()}catch(_:Exception){JSONArray()};Api.get(server,"/wp-json/aft/v1/parent-zone",token){_,zbody->runOnUiThread{val zone=try{JSONObject(zbody).optJSONObject("zone")}catch(_:Exception){null};Api.get(server,"/wp-json/aft/v1/parent-alerts",token){_,abody->runOnUiThread{var alertText="";try{val arr=JSONObject(abody).optJSONArray("alerts")?:JSONArray();if(arr.length()>0)alertText=" • ⚠ "+arr.getJSONObject(0).optString("message","تنبيه جديد")}catch(_:Exception){};info.text="آخر تحديث: "+updated+" • البطارية: "+if(bat>=0)bat.toString()+"%" else "—"+alertText;web.loadDataWithBaseURL(null,html(lat,lng,acc,pts,zone),"text/html","UTF-8",null)}}}}}}catch(e:Exception){info.text="بيانات الموقع غير صالحة"}}}}
 private fun html(lat:Double,lng:Double,acc:Double,pts:JSONArray,zone:JSONObject?)="""<!doctype html><html lang="ar" dir="rtl"><head><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css"><style>html,body,#m{height:100%;margin:0}.badge{position:absolute;z-index:9999;top:12px;right:12px;background:#fff;padding:10px 14px;border-radius:14px;box-shadow:0 3px 15px #0002;font-family:sans-serif}</style></head><body><div id="m"></div><div class="badge">أمان أطفالي</div><script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"></script><script>const map=L.map('m').setView(["""+lat+""","""+lng+""],16);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap'}).addTo(map);L.marker(["""+lat+""","""+lng+"""]).addTo(map).bindPopup('آخر موقع للطفل').openPopup();L.circle(["""+lat+""","""+lng+"""],{radius:"""+acc.coerceAtLeast(5.0)+""",color:'#2563eb',fillOpacity:.12}).addTo(map);const points="""+pts.toString()+""";if(points.length>1){L.polyline(points.map(p=>[p.latitude,p.longitude]),{weight:5,opacity:.85}).addTo(map);}const zone="""+(zone?.toString()?:"null")+""";if(zone){L.circle([zone.latitude,zone.longitude],{radius:zone.radius,color:'#16a34a',fillOpacity:.08,weight:3}).addTo(map).bindPopup('المنطقة الآمنة: '+zone.name);}</script></body></html>"""
 override fun onDestroy(){timer?.cancel();super.onDestroy()}
}